Add VLAN support

diff --git a/hook b/hook
--- a/hook
+++ b/hook
@@ -10,25 +10,38 @@ run_hook () {
     fi
     unset IFS
 
+    IFS="."
+    set -- ${interface}
+    parent="$1" vlan="$2"
+    if [ -n "${vlan}" ]; then
+      if ip link add link "${parent}" name "${interface}" type vlan id "${vlan}"; then
+        ip link set dev "${parent}" up
+      else
+        printf "%s\n" "Failed to add VLAN device"
+      fi
+    fi
+    unset IFS
+
     if [ -h "/sys/class/net/${interface}" ]; then
       if [ "${method}" = "dhcp" ]; then
         if dhclient -1 -lf /run/dhclient.leases "${interface}"; then
           killall dhclient
         else
-          printf "Failed to request address via DHCP\n\n"
+          printf "%s\n" "Failed to request address via DHCP"
         fi
       else
           ip link set dev "${interface}" up
           ip addr add "${address}/${subnet}" dev "${interface}"
           printf "%s: %s\n" "Address" "${address}" "Subnet" "${subnet}"
           ip route add default via "${gateway}" dev "${interface}"
-          printf "%s: %s\n\n" "Gateway" "${gateway}"
+          printf "%s: %s\n" "Gateway" "${gateway}"
+          printf "\n"
       fi
     else
-      printf "Network device unavailable\n\n"
+      printf "%s\n" "Network device unavailable"
     fi
   else
-    printf "Network configuration unavailable\n\n"
+    printf "%s\n" "Network configuration unavailable"
   fi
 
   if [ -n "${cryptdevice}" ]; then
@@ -39,15 +52,22 @@ run_hook () {
 
     printf "%s=%s\n" "cryptdevice" "${cryptdevice}" > /run/cryptdevice
     if dropbear -E -s -j -k $(printf -- " -r %s" $(ls /etc/dropbear/*_host_key)) -c unlock 2> /dev/null; then
-      printf "%s\n\n" "SSH server is running..."
+      printf "%s\n" "SSH server is running..."
     else
-      printf "%s\n\n" "Failed to start SSH server"
+      printf "%s\n" "Failed to start SSH server"
     fi
+    printf "\n"
 
     unlock
 
     killall dropbear
+
+    if [ -n "${vlan}" ]; then
+      if ! ip link delete "${interface}"; then
+        printf "%s\n" "Failed to delete VLAN device"
+      fi
+    fi
   else
-    printf "Device configuration unavailable\n"
+    printf "%s\n" "Device configuration unavailable"
   fi
 }
